module.exports = {
  content: ["*.html", "js/**/*.js"],
  css: ["css/**/*.css"],
  safelist: {
    standard: [
      /^cc--/,
      /^cm__/,
      /^pm__/,
      /^slick-/,
      /^navbar-/,
      /^dropdown-/,
      /^badge-/,
      /^collapse$/,
      /^collapsing$/,
      /^show$/,
      /^active$/,
      /^opened$/,
      /^scrolling$/,
      /^up$/,
      /^mobile-menu-open$/,
    ],
    deep: [/^cc-/, /^slick-/, /^navbar/, /^dropdown/],
    greedy: [/focus-visible/],
  },
};
