name: Build Beta

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Print build name
        run: echo "$GITHUB_ACTOR is building '$GITHUB_REPOSITORY' (commit $GITHUB_SHA)"
      
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag website

      - name: Auth for GitHub's Docker repository
        env:
          USER: ${{ secrets.PACKAGES_USER }}
          TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: docker login docker.pkg.github.com -u $USER -p $TOKEN

      - name: Tag Docker image
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          echo "Tagging images with version '$VERSION'..."
          docker tag website docker.pkg.github.com/$GITHUB_REPOSITORY/website:"$VERSION".beta
          docker tag website docker.pkg.github.com/$GITHUB_REPOSITORY/website:latest_beta
          docker tag website appifyhub/website:"$VERSION".beta
          docker tag website appifyhub/website:latest_beta

      - name: Publish Docker images to GitHub
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          echo "Publishing images with version '$VERSION'..."
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/website:"$VERSION".beta
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/website:latest_beta

      - name: Publish Docker images to DockerHub
        id: docker_publish
        env:
          USER: ${{ secrets.DOCKER_HUB_USER }}
          TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          docker login docker.io -u $USER -p $TOKEN
          echo "Publishing images with version '$VERSION'..."
          docker push appifyhub/website:"$VERSION".beta
          docker push appifyhub/website:latest_beta
          echo ::set-output name=website_version::"$VERSION"

      - name: Publish to GitHub Releases
        env:
          ARTIFACT: "website"
          BUILD_QUALITY: "Beta"
          VERSION: ${{ steps.docker_publish.outputs.website_version }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        run: |
          pip install -r .github/scripts/requirements.txt
          python .github/scripts/github_release.py

      - name: Comment build information
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
          PR_NUMBER: ${{ github.event.number }}
          VERSION: ${{ steps.docker_publish.outputs.website_version }}
          DOCKER_IMG: "docker pull appifyhub/website"
        run: |
          NL=$'\n'
          CODE='```'
          DOCKER_VERSIONED="$DOCKER_IMG:$VERSION.beta"
          DOCKER_LATEST="# Valid until a new build${NL}${DOCKER_IMG}:latest_beta"
          CODE_BLOCK="${CODE}shell${NL}${DOCKER_LATEST}${NL}${DOCKER_VERSIONED}${NL}${CODE}"
          JOB="[${GITHUB_RUN_ID}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})"
          NOTIFICATION="Build ${JOB} complete for ${GITHUB_SHA}.${NL}${NL}${CODE_BLOCK}${NL}"
          gh pr comment "$PR_NUMBER" -b "$NOTIFICATION"

      - name: Deploy to staging
        env:
          DEPLOY_API: ${{ secrets.DEPLOY_API }}
          DEPLOY_APP: ${{ secrets.DEPLOY_APP }}
          DEPLOY_ARGS: ${{ secrets.DEPLOY_ARGS }}
          DEPLOY_SPACE_STG: ${{ secrets.DEPLOY_SPACE_STG }}
          DEPLOY_AUTH_STG: ${{ secrets.DEPLOY_AUTH_STG }}
          DEPLOY_MODE: ${{ secrets.DEPLOY_MODE }}
          DEPLOY_SPEC: ${{ secrets.DEPLOY_SPEC }}
          DEPLOY_TAGS: ${{ secrets.DEPLOY_TAGS }}
        run: |
          CMD="${DEPLOY_SPEC}$(date +'%s')${DEPLOY_TAGS}"
          URL_STG="${DEPLOY_API}/${DEPLOY_SPACE_STG}/deployments/${DEPLOY_APP}?${DEPLOY_ARGS}"
          curl -s --location --request PATCH "${URL_STG}" --insecure \
          --header "${DEPLOY_MODE}" \
          --header "${DEPLOY_AUTH_STG}" \
          --data-raw "${CMD}" \
          > /dev/null
