name: Build QA

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Print build name
        run: echo "$GITHUB_ACTOR is building PR#$PR_NUMBER in '$GITHUB_REPOSITORY' (commit $GITHUB_SHA)"

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag website

      - name: Auth for GitHub's Docker repository
        env:
          USER: ${{ secrets.PACKAGES_USER }}
          TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: docker login docker.pkg.github.com -u $USER -p $TOKEN

      - name: Tag Docker image
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          echo "Tagging images with version '$VERSION'..."
          docker tag website docker.pkg.github.com/$GITHUB_REPOSITORY/website:"$VERSION".pr_$PR_NUMBER
          docker tag website docker.pkg.github.com/$GITHUB_REPOSITORY/website:latest_pr
          docker tag website appifyhub/website:"$VERSION".pr_$PR_NUMBER
          docker tag website appifyhub/website:latest_pr

      - name: Publish Docker images to GitHub
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          echo "Publishing images with version '$VERSION'..."
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/website:"$VERSION".pr_$PR_NUMBER
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/website:latest_pr

      - name: Publish Docker images to DockerHub
        id: docker_publish
        env:
          USER: ${{ secrets.DOCKER_HUB_USER }}
          TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          VERSION=$(cat .version | tr -d '[:space:]')
          docker login docker.io -u $USER -p $TOKEN
          echo "Publishing images with version '$VERSION'..."
          docker push appifyhub/website:"$VERSION".pr_$PR_NUMBER
          docker push appifyhub/website:latest_pr
          echo ::set-output name=website_version::"$VERSION"

      - name: Comment build information
        env:
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
          GITHUB_SERVER_URL: ${{ env.GITHUB_SERVER_URL }}
          PR_NUMBER: ${{ github.event.number }}
          VERSION: ${{ steps.docker_publish.outputs.website_version }}
          DOCKER_IMG: "docker pull appifyhub/website"
        run: |
          NL=$'\n'
          CODE='```'
          DOCKER_VERSIONED="$DOCKER_IMG:$VERSION.pr_$PR_NUMBER"
          DOCKER_LATEST="# Valid until a new build${NL}${DOCKER_IMG}:latest_pr"
          CODE_BLOCK="${CODE}shell${NL}${DOCKER_LATEST}${NL}${DOCKER_VERSIONED}${NL}${CODE}"
          JOB="[${GITHUB_RUN_ID}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID})"
          NOTIFICATION="Build ${JOB} complete for ${GITHUB_SHA}.${NL}${NL}${CODE_BLOCK}${NL}"
          gh pr comment "$PR_NUMBER" -b "$NOTIFICATION"
